[phases.instalar_postgres_18]
dependsOn = ["setup"]
cmds = [
    "apt-get update",
    "apt-get install -y wget ca-certificates",
    "mkdir -p /etc/apt/keyrings",
    "wget --quiet -O /etc/apt/keyrings/postgresql.asc https://www.postgresql.org/media/keys/ACCC4CF8.asc",
    "echo 'deb [signed-by=/etc/apt/keyrings/postgresql.asc] http://apt.postgresql.org/pub/repos/apt/ noble-pgdg main' > /etc/apt/sources.list.d/postgresql.list",
    "apt-get update",
    "apt-get install -y postgresql-client-18"
]